name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  camera: ^0.10.0+1
  cross_file: ^0.3.3+1
  flutter:
    sdk: flutter
  rive: ^0.9.1
  tensorflow_models:
    path: ../

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/
  