name: download_repository
description: Repository responsible for fetching and downloading a file.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.12

dependencies:
  camera: ^0.10.0+3
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
