name: tensorflow_models_web

on:
  pull_request:
    paths:
      - "packages/tensorflow_models/tensorflow_models_web/**"
      - ".github/workflows/tensorflow_models_web.yaml"
    branches:
      - main

jobs:
  build:
    defaults:
      run:
        working-directory: packages/tensorflow_models/tensorflow_models_web

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.12
          channel: "stable"
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: âœ¨ Check Formatting
        run: flutter format --set-exit-if-changed lib test

      - name: ğŸ•µï¸ Analyze
        run: flutter analyze lib test

      - name: Run Chromedriver
        run: |
          git clone https://github.com/felangel/web_installers
          cd web_installers/packages/web_drivers
          dart pub get
          dart lib/web_driver_installer.dart chromedriver --install-only
          ./chromedriver/chromedriver --port=4444 &

      - name: Integration Tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=test/src/tensorflow_models_plugin_test.dart -d web-server --browser-name=chrome
